import { randomBytes } from 'node:crypto';
import type * as vscode from 'vscode';

export type FormStatusAction =
  | 'retry' | 'rebuild' | 'chooseAssembly' | 'viewCode' | 'clearCache' | 'restart' | 'refresh';

export interface FormStatusSnapshot {
  documentId: string;
  revision: number;
  title: string;
  fields: readonly { label: string; value: string }[];
  diagnostics: readonly {
    code: string;
    severity: 'info' | 'warning' | 'error';
    message: string;
    target?: string;
    actions: readonly string[];
  }[];
  adapterRows?: readonly { id: string; state: string; message: string }[];
}

export interface FormStatusLabels {
  title: string;
  fieldsHeading: string;
  diagnosticsHeading: string;
  adaptersHeading: string;
  noDiagnostics: string;
  noAdapters: string;
  details: string;
  target: string;
  loading: string;
  loadFailed: string;
  actionFailed: string;
  severity: Readonly<Record<'info' | 'warning' | 'error', string>>;
  actions: Readonly<Record<FormStatusAction, string>>;
  language?: string;
}

const ACTIONS: readonly FormStatusAction[] = [
  'retry', 'rebuild', 'chooseAssembly', 'viewCode', 'clearCache', 'restart', 'refresh',
];

function isAction(value: unknown): value is FormStatusAction {
  return typeof value === 'string' && ACTIONS.includes(value as FormStatusAction);
}

/** Only host-owned diagnostic decisions grant an action. Webview messages never supply a target or command. */
export function authorizeFormStatusAction(
  message: unknown,
  snapshot: FormStatusSnapshot | undefined,
): FormStatusAction | undefined {
  if (typeof message !== 'object' || message === null || Array.isArray(message)) return undefined;
  const candidate = message as Record<string, unknown>;
  if (candidate.type !== 'formStatusAction' || !isAction(candidate.action)) return undefined;
  if (!snapshot) {
    return candidate.action === 'refresh' && candidate.documentId === null && candidate.revision === null
      ? 'refresh' : undefined;
  }
  if (!Number.isSafeInteger(snapshot.revision) || snapshot.revision < 0
    || candidate.documentId !== snapshot.documentId || candidate.revision !== snapshot.revision) return undefined;
  if (candidate.action === 'refresh') return 'refresh';
  return snapshot.diagnostics.some(diagnostic => diagnostic.actions.includes(candidate.action as string))
    ? candidate.action : undefined;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, character => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[character]!));
}

/** Local display only: callers supply catalogue messages, never raw source or exception dumps. */
export function renderFormStatusHtml(
  snapshot: FormStatusSnapshot | undefined,
  labels: FormStatusLabels,
  nonce: string,
  notice = '',
  error = false,
  busy = false,
): string {
  // Nonces are generated by the host; reject accidental interpolation of arbitrary CSP syntax.
  if (!/^[a-zA-Z0-9_-]{16,}$/.test(nonce)) throw new Error('Invalid form status nonce');
  const e = escapeHtml;
  const button = (action: FormStatusAction): string =>
    `<button type="button" data-action="${action}"${busy ? ' disabled' : ''}>${e(labels.actions[action])}</button>`;
  const fields = (snapshot?.fields ?? []).map(field =>
    `<div class="field"><dt>${e(field.label)}</dt><dd>${e(field.value)}</dd></div>`).join('');
  const diagnostics = snapshot?.diagnostics.map(diagnostic => {
    const severity = ['info', 'warning', 'error'].includes(diagnostic.severity) ? diagnostic.severity : 'info';
    const actions = [...new Set(diagnostic.actions)].filter(isAction).filter(action => action !== 'refresh');
    return `<li class="diagnostic ${severity}">
      <div class="diagnostic-heading"><strong>${e(labels.severity[severity])}</strong><code>${e(diagnostic.code)}</code></div>
      <p>${e(diagnostic.message)}</p>
      ${diagnostic.target ? `<details><summary>${e(labels.details)}</summary><dl>
        <div class="field"><dt>${e(labels.target)}</dt><dd>${e(diagnostic.target)}</dd></div></dl></details>` : ''}
      ${actions.length ? `<div class="actions">${actions.map(button).join('')}</div>` : ''}
    </li>`;
  }).join('');
  const adapters = snapshot?.adapterRows?.map(adapter => `<li>
    <p><strong>${e(adapter.id)}</strong> <span class="adapter-state">${e(adapter.state)}</span></p>
    <p>${e(adapter.message)}</p></li>`).join('');
  return `<!DOCTYPE html>
<html lang="${e(labels.language ?? 'en')}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'; base-uri 'none'; form-action 'none';">
<title>${e(labels.title)}</title>
<style nonce="${nonce}">
  body { color: var(--vscode-foreground); background: var(--vscode-editor-background); font: var(--vscode-font-size, 13px) var(--vscode-font-family, sans-serif); margin: 0; padding: 24px; }
  main { max-width: 1000px; margin: 0 auto; }
  h1 { font-size: 1.65em; margin: 0; overflow-wrap: anywhere; }
  h2, summary { font-size: 1.15em; }
  header { display: flex; gap: 16px; align-items: flex-start; justify-content: space-between; margin-bottom: 20px; }
  button { font: inherit; color: var(--vscode-button-foreground); background: var(--vscode-button-background); border: 1px solid var(--vscode-contrastBorder, transparent); padding: 6px 12px; cursor: pointer; }
  button:hover { background: var(--vscode-button-hoverBackground); }
  button:disabled { opacity: .6; cursor: wait; }
  button:focus-visible, summary:focus-visible { outline: 2px solid var(--vscode-focusBorder); outline-offset: 3px; }
  details, section { margin-block: 18px; }
  summary { cursor: pointer; padding-block: 5px; }
  dl { margin: 8px 0; }
  .field { display: grid; grid-template-columns: minmax(120px, 1fr) minmax(0, 3fr); gap: 10px; padding-block: 6px; }
  dt { font-weight: 600; }
  dd { margin: 0; white-space: pre-wrap; overflow-wrap: anywhere; }
  ul { padding: 0; list-style: none; }
  li { border: 1px solid var(--vscode-panel-border, var(--vscode-contrastBorder)); padding: 12px; margin-block: 12px; }
  .diagnostic-heading, .actions { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; }
  .diagnostic p, .adapter-state, code { white-space: pre-wrap; overflow-wrap: anywhere; }
  .error > .diagnostic-heading, [role="alert"] { color: var(--vscode-errorForeground); }
  .warning > .diagnostic-heading { color: var(--vscode-editorWarning-foreground); }
  .actions { margin-top: 12px; }
  @media (max-width: 500px) { body { padding: 14px; } .field { grid-template-columns: 1fr; gap: 4px; } header { flex-wrap: wrap; } }
</style></head>
<body><main id="form-status" aria-busy="${busy}" data-document-id="${e(snapshot?.documentId ?? '')}" data-revision="${snapshot?.revision ?? ''}">
  <header><h1>${e(snapshot?.title ?? labels.title)}</h1>${button('refresh')}</header>
  <p id="status-notice" role="${error ? 'alert' : 'status'}" aria-live="${error ? 'assertive' : 'polite'}">${e(notice)}</p>
  ${snapshot ? `<details open><summary>${e(labels.fieldsHeading)}</summary><dl>${fields}</dl></details>
  <section aria-labelledby="diagnostics-heading"><h2 id="diagnostics-heading">${e(labels.diagnosticsHeading)}</h2>
    ${diagnostics ? `<ul>${diagnostics}</ul>` : `<p>${e(labels.noDiagnostics)}</p>`}</section>
  <details><summary>${e(labels.adaptersHeading)}</summary>${adapters ? `<ul>${adapters}</ul>` : `<p>${e(labels.noAdapters)}</p>`}</details>` : ''}
</main>
<script nonce="${nonce}">
  (() => {
    const vscode = acquireVsCodeApi();
    const root = document.getElementById('form-status');
    const setBusy = busy => {
      root.setAttribute('aria-busy', String(busy));
      for (const button of root.querySelectorAll('button[data-action]')) button.disabled = busy;
    };
    root.addEventListener('click', event => {
      const button = event.target.closest('button[data-action]');
      if (!button || button.disabled) return;
      setBusy(true);
      vscode.postMessage({
        type: 'formStatusAction', action: button.dataset.action,
        documentId: root.dataset.revision === '' ? null : root.dataset.documentId,
        revision: root.dataset.revision === '' ? null : Number(root.dataset.revision),
      });
    });
    window.addEventListener('message', event => {
      if (event.data?.type === 'formStatusBusy' && typeof event.data.busy === 'boolean') setBusy(event.data.busy);
    });
  })();
</script></body></html>`;
}

/** Bind one panel without starting an engine or depending on the active editor. */
export function bindFormStatusView(
  panel: vscode.WebviewPanel,
  getSnapshot: () => Promise<FormStatusSnapshot>,
  onAction: (action: string, snapshot: FormStatusSnapshot) => Promise<void>,
  labels: FormStatusLabels,
): void {
  let disposed = false;
  let generation = 0;
  let busy = false;
  let latest: FormStatusSnapshot | undefined;
  let displayedNotice = '';
  let displayedError = false;
  const render = (notice = '', error = false): void => {
    displayedNotice = notice;
    displayedError = error;
    // Replacing HTML reloads the client asynchronously. Publish the final enabled state in HTML itself,
    // rather than relying on an unlock message that could arrive before the new script starts listening.
    if (!disposed && !busy) panel.webview.html = renderFormStatusHtml(latest, labels, randomBytes(24).toString('hex'), notice, error);
  };
  const refresh = async (): Promise<FormStatusSnapshot | undefined> => {
    const requestedGeneration = ++generation;
    try {
      const snapshot = await getSnapshot();
      if (disposed || requestedGeneration !== generation) return undefined;
      latest = snapshot;
      render();
      return snapshot;
    } catch {
      if (!disposed && requestedGeneration === generation) {
        latest = undefined;
        render(labels.loadFailed, true);
      }
      return undefined;
    }
  };
  const listener = panel.webview.onDidReceiveMessage(async (message: unknown) => {
    if (disposed || busy) return;
    const action = authorizeFormStatusAction(message, latest);
    if (!action) {
      // Restore buttons after a stale click without executing the requested action.
      await Promise.resolve(panel.webview.postMessage({ type: 'formStatusBusy', busy: false })).catch(() => false);
      return;
    }
    busy = true;
    try {
      const snapshot = await refresh();
      if (disposed || !snapshot || action === 'refresh') return;
      // Availability and revision can change while an open status panel displays an earlier snapshot.
      if (authorizeFormStatusAction(message, snapshot) !== action) return;
      await onAction(action, snapshot);
      if (!disposed) await refresh();
    } catch {
      render(labels.actionFailed, true);
    } finally {
      busy = false;
      render(displayedNotice, displayedError);
    }
  });
  panel.onDidDispose(() => {
    disposed = true;
    generation++;
    latest = undefined;
    listener.dispose();
  });
  render(labels.loading);
  void refresh();
}

export function showFormStatusView(
  _extensionUri: vscode.Uri,
  getSnapshot: () => Promise<FormStatusSnapshot>,
  onAction: (action: string, snapshot: FormStatusSnapshot) => Promise<void>,
  labels: FormStatusLabels,
): vscode.WebviewPanel {
  // Keep pure rendering and authorization usable in unit tests without the Extension Host runtime.
  const host = require('vscode') as typeof vscode;
  const panel = host.window.createWebviewPanel('winformsDesigner.formStatus', labels.title, host.ViewColumn.Active, {
    enableScripts: true,
    localResourceRoots: [],
  });
  bindFormStatusView(panel, getSnapshot, onAction, labels);
  return panel;
}
