// <auto-generated>
// Generated by scripts/generate-v2-protocol.mjs from docs/v2/designer-protocol-v2.schema.json.
// Schema SHA-256: e80c86785fa1563da5d544561ea32efc8ab08830a57889bb85c4c535bb79e6fa
// </auto-generated>

export const V2_PROTOCOL_ID = "designer-protocol-v2" as const;
export const V2_PROTOCOL_CURRENT_VERSION = 2 as const;
export const V2_PROTOCOL_MINIMUM_SUPPORTED_VERSION = 1 as const;
export const V2_PROTOCOL_MAX_PAYLOAD_BYTES = 1048576 as const;
export const V2_PROTOCOL_MAX_CAPABILITIES = 64 as const;
export const V2_PROTOCOL_MAX_RESOURCE_FINGERPRINTS = 64 as const;
export const V2_PROTOCOL_MAX_IDENTIFIER_LENGTH = 128 as const;
export const V2_PROTOCOL_MAX_OUTCOME_MESSAGE_LENGTH = 4096 as const;
export const V2_PROTOCOL_SCHEMA_SHA256 = "e80c86785fa1563da5d544561ea32efc8ab08830a57889bb85c4c535bb79e6fa" as const;

export const V2_PROTOCOL_CAPABILITIES = [
  "protocol.envelope-v2",
  "protocol.outcome-v2",
  "protocol.n-minus-one",
  "document.source-fingerprint",
  "document.resource-fingerprint",
  "request.deadline",
  "request.cancellation-token",
  "payload.byte-limit",
  "outcome.ok",
  "outcome.partial",
  "outcome.stale",
  "outcome.cancelled",
  "outcome.unsupported",
  "outcome.refused",
  "outcome.fault"
] as const;

export const V2_PROTOCOL_OUTCOME_KINDS = [
  "ok",
  "partial",
  "stale",
  "cancelled",
  "unsupported",
  "refused",
  "fault"
] as const;

export const V2_PROTOCOL_OUTCOME_CODES = [
  "OK",
  "PARTIAL_RESULT",
  "PARTIAL_UPDATE",
  "STALE_SOURCE",
  "STALE_RESOURCE",
  "CANCELLED",
  "UNSUPPORTED_CAPABILITY",
  "UNSUPPORTED_OPERATION",
  "UNKNOWN_REQUIRED_CAPABILITY",
  "PROTOCOL_VERSION_UNSUPPORTED",
  "PAYLOAD_TOO_LARGE",
  "INVALID_ENVELOPE",
  "INTERNAL_ERROR",
  "UNHANDLED_EXCEPTION"
] as const;

export type V2ProtocolCapability = typeof V2_PROTOCOL_CAPABILITIES[number];
export type V2ProtocolOutcomeKind = typeof V2_PROTOCOL_OUTCOME_KINDS[number];
export type V2ProtocolOutcomeCode = typeof V2_PROTOCOL_OUTCOME_CODES[number];
export type V2ProtocolMessageKind = "request" | "response";

export interface V2Fingerprint {
  algorithm: 'sha256';
  artifactId: string;
  value: string;
  byteLength: number;
}

export interface V2ProtocolEnvelope {
  protocolId: typeof V2_PROTOCOL_ID;
  protocolVersion: number;
  messageKind: V2ProtocolMessageKind;
  buildId: string;
  sessionId: string;
  documentId: string;
  requestId: string;
  traceId: string;
  commandId?: string;
  documentRevision: string;
  renderGeneration: number;
  sourceFingerprint: V2Fingerprint;
  resourceFingerprints: V2Fingerprint[];
  deadlineUnixMilliseconds: number;
  cancellationToken: string;
  capabilities: string[];
  requiredCapabilities: string[];
  payloadContentType: 'application/json';
  payloadBytes: number;
  payloadJson: string;
}

export interface V2ProtocolOutcome {
  kind: V2ProtocolOutcomeKind;
  requestId: string;
  traceId: string;
  code: V2ProtocolOutcomeCode;
  message: string;
  retryable: boolean;
  diagnosticId: string;
  expectedSourceFingerprint?: V2Fingerprint;
  actualSourceFingerprint?: V2Fingerprint;
}

export type V2EnvelopeValidation =
  | { ok: true; envelope: V2ProtocolEnvelope }
  | { ok: false; outcome: V2ProtocolOutcome };

const identifierRegex = new RegExp("^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$");
const sha256Regex = new RegExp("^[a-f0-9]{64}$");
const capabilityRegex = new RegExp("^[a-z][a-z0-9.-]{1,95}$");
const capabilitySet = new Set<string>(V2_PROTOCOL_CAPABILITIES);
const outcomeKindSet = new Set<string>(V2_PROTOCOL_OUTCOME_KINDS);
const outcomeCodeSet = new Set<string>(V2_PROTOCOL_OUTCOME_CODES);
const outcomeCodesByKind = new Map<string, ReadonlySet<string>>([
  ["ok", new Set(["OK"])],
  ["partial", new Set(["PARTIAL_RESULT", "PARTIAL_UPDATE"])],
  ["stale", new Set(["STALE_SOURCE", "STALE_RESOURCE"])],
  ["cancelled", new Set(["CANCELLED"])],
  ["unsupported", new Set(["UNSUPPORTED_CAPABILITY", "UNSUPPORTED_OPERATION"])],
  ["refused", new Set(["UNKNOWN_REQUIRED_CAPABILITY", "PROTOCOL_VERSION_UNSUPPORTED", "PAYLOAD_TOO_LARGE", "INVALID_ENVELOPE"])],
  ["fault", new Set(["INTERNAL_ERROR", "UNHANDLED_EXCEPTION"])]
]);
const envelopeRequiredKeys = new Set([
  "protocolId",
  "protocolVersion",
  "messageKind",
  "buildId",
  "sessionId",
  "documentId",
  "requestId",
  "traceId",
  "documentRevision",
  "renderGeneration",
  "sourceFingerprint",
  "resourceFingerprints",
  "deadlineUnixMilliseconds",
  "cancellationToken",
  "capabilities",
  "requiredCapabilities",
  "payloadContentType",
  "payloadBytes",
  "payloadJson"
]);
const envelopeAllowedKeys = new Set([
  "protocolId",
  "protocolVersion",
  "messageKind",
  "buildId",
  "sessionId",
  "documentId",
  "requestId",
  "traceId",
  "documentRevision",
  "renderGeneration",
  "sourceFingerprint",
  "resourceFingerprints",
  "deadlineUnixMilliseconds",
  "cancellationToken",
  "capabilities",
  "requiredCapabilities",
  "payloadContentType",
  "payloadBytes",
  "payloadJson",
  "commandId"
]);
const fingerprintKeys = new Set([
  "algorithm",
  "artifactId",
  "value",
  "byteLength"
]);
const outcomeKeys = new Set([
  'kind',
  'requestId',
  'traceId',
  'code',
  'message',
  'retryable',
  'diagnosticId',
  'expectedSourceFingerprint',
  'actualSourceFingerprint'
]);

export function createV2ProtocolEnvelope(init: Omit<V2ProtocolEnvelope, 'protocolId' | 'protocolVersion' | 'payloadContentType' | 'payloadBytes'> & { protocolVersion?: number }): V2ProtocolEnvelope {
  return {
    ...init,
    protocolId: V2_PROTOCOL_ID,
    protocolVersion: init.protocolVersion ?? V2_PROTOCOL_CURRENT_VERSION,
    payloadContentType: 'application/json',
    payloadBytes: payloadByteCount(init.payloadJson),
  };
}

export function createV2Fingerprint(artifactId: string, value: string, byteLength: number): V2Fingerprint {
  return { algorithm: 'sha256', artifactId, value, byteLength };
}

export function validateV2ProtocolEnvelope(value: unknown, supportedCapabilities: readonly string[] = V2_PROTOCOL_CAPABILITIES): V2EnvelopeValidation {
  const failure = validateEnvelopeShape(value, supportedCapabilities);
  if (failure) {
    return { ok: false, outcome: failure };
  }
  return { ok: true, envelope: value as V2ProtocolEnvelope };
}

export function validateV2ProtocolOutcome(value: unknown): value is V2ProtocolOutcome {
  if (!isRecord(value) || !hasOnlyKeys(value, outcomeKeys)) {
    return false;
  }
  if (!outcomeKindSet.has(asString(value.kind)) || !outcomeCodeSet.has(asString(value.code))) {
    return false;
  }
  if (!outcomeCodesByKind.get(asString(value.kind))?.has(asString(value.code))) {
    return false;
  }
  if (!validIdentifier(asString(value.requestId)) || !validIdentifier(asString(value.traceId))) {
    return false;
  }
  if (typeof value.message !== 'string' || Buffer.byteLength(value.message, 'utf8') > V2_PROTOCOL_MAX_OUTCOME_MESSAGE_LENGTH) {
    return false;
  }
  if (typeof value.retryable !== 'boolean' || !validIdentifier(asString(value.diagnosticId))) {
    return false;
  }
  if (value.expectedSourceFingerprint !== undefined && !isFingerprint(value.expectedSourceFingerprint)) {
    return false;
  }
  if (value.actualSourceFingerprint !== undefined && !isFingerprint(value.actualSourceFingerprint)) {
    return false;
  }
  return true;
}

export function makeV2ProtocolRefusal(requestId: string, traceId: string, code: 'UNKNOWN_REQUIRED_CAPABILITY' | 'PROTOCOL_VERSION_UNSUPPORTED' | 'PAYLOAD_TOO_LARGE' | 'INVALID_ENVELOPE', message: string): V2ProtocolOutcome {
  return { kind: 'refused', requestId, traceId, code, message, retryable: false, diagnosticId: code };
}

export function payloadByteCount(payloadJson: string): number {
  return Buffer.byteLength(payloadJson, 'utf8');
}

function validateEnvelopeShape(value: unknown, supportedCapabilities: readonly string[]): V2ProtocolOutcome | null {
  const requestId = isRecord(value) && typeof value.requestId === 'string' && validIdentifier(value.requestId) ? value.requestId : 'invalid-request';
  const traceId = isRecord(value) && typeof value.traceId === 'string' && validIdentifier(value.traceId) ? value.traceId : 'invalid-trace';
  if (!isRecord(value) || !hasOnlyKeys(value, envelopeAllowedKeys)) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Envelope has unknown or missing fields.');
  }
  for (const key of envelopeRequiredKeys) {
    if (!(key in value)) {
      return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', `Envelope is missing required field '${key}'.`);
    }
  }
  const envelope = value;
  const protocolVersion = envelope.protocolVersion;
  if (envelope.protocolId !== V2_PROTOCOL_ID || typeof protocolVersion !== 'number' || !Number.isInteger(protocolVersion)) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Protocol identity is invalid.');
  }
  if (protocolVersion < V2_PROTOCOL_MINIMUM_SUPPORTED_VERSION || protocolVersion > V2_PROTOCOL_CURRENT_VERSION) {
    return makeV2ProtocolRefusal(requestId, traceId, 'PROTOCOL_VERSION_UNSUPPORTED', `Unsupported protocol version ${protocolVersion}.`);
  }
  if (envelope.messageKind !== 'request' && envelope.messageKind !== 'response') {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Message kind is invalid.');
  }
  if (!validIdentifier(envelope.buildId) || !validIdentifier(envelope.sessionId) || !validIdentifier(envelope.documentId) || !validIdentifier(envelope.requestId) || !validIdentifier(envelope.traceId) || !validOptionalIdentifier(envelope.commandId) || !validIdentifier(envelope.documentRevision) || !validIdentifier(envelope.cancellationToken)) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'One or more identifiers are invalid.');
  }
  if (!Number.isSafeInteger(envelope.renderGeneration) || (envelope.renderGeneration as number) < 0) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Render generation is invalid.');
  }
  if (!isFingerprint(envelope.sourceFingerprint) || !validResourceFingerprints(envelope.resourceFingerprints, envelope.sourceFingerprint.artifactId)) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Source or resource fingerprints are invalid.');
  }
  const deadlineUnixMilliseconds = envelope.deadlineUnixMilliseconds;
  if (typeof deadlineUnixMilliseconds !== 'number' || !Number.isSafeInteger(deadlineUnixMilliseconds) || deadlineUnixMilliseconds <= 0) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Deadline is invalid.');
  }
  const capabilities = envelope.capabilities;
  const requiredCapabilities = envelope.requiredCapabilities;
  if (!validCapabilities(capabilities) || !validCapabilities(requiredCapabilities)) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Capabilities are invalid.');
  }
  const supported = new Set(supportedCapabilities);
  const unknownRequired = requiredCapabilities.find((capability) => !capabilitySet.has(capability) || !supported.has(capability));
  if (unknownRequired) {
    return makeV2ProtocolRefusal(requestId, traceId, 'UNKNOWN_REQUIRED_CAPABILITY', `Required capability is not supported: ${unknownRequired}`);
  }
  const payloadJson = envelope.payloadJson;
  const payloadBytes = envelope.payloadBytes;
  if (envelope.payloadContentType !== 'application/json' || typeof payloadJson !== 'string' || typeof payloadBytes !== 'number' || !Number.isInteger(payloadBytes)) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Payload metadata is invalid.');
  }
  const actualPayloadBytes = payloadByteCount(payloadJson);
  if (payloadBytes !== actualPayloadBytes) {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Payload byte count does not match payloadJson.');
  }
  if (actualPayloadBytes > V2_PROTOCOL_MAX_PAYLOAD_BYTES) {
    return makeV2ProtocolRefusal(requestId, traceId, 'PAYLOAD_TOO_LARGE', 'Payload exceeds the v2 envelope byte limit.');
  }
  try {
    JSON.parse(payloadJson);
  } catch {
    return makeV2ProtocolRefusal(requestId, traceId, 'INVALID_ENVELOPE', 'Payload is not valid JSON.');
  }
  return null;
}

function validCapabilities(value: unknown): value is string[] {
  if (!Array.isArray(value) || value.length > V2_PROTOCOL_MAX_CAPABILITIES) {
    return false;
  }
  const seen = new Set<string>();
  for (const item of value) {
    if (typeof item !== 'string' || !capabilityRegex.test(item) || seen.has(item)) {
      return false;
    }
    seen.add(item);
  }
  return true;
}

function isFingerprint(value: unknown): value is V2Fingerprint {
  if (!isRecord(value) || !hasOnlyKeys(value, fingerprintKeys)) {
    return false;
  }
  const byteLength = value.byteLength;
  return value.algorithm === 'sha256'
    && validIdentifier(value.artifactId)
    && typeof value.value === 'string'
    && sha256Regex.test(value.value)
    && typeof byteLength === 'number'
    && Number.isSafeInteger(byteLength)
    && byteLength >= 0;
}

function validResourceFingerprints(value: unknown, sourceArtifactId: string): value is V2Fingerprint[] {
  if (!Array.isArray(value) || value.length > V2_PROTOCOL_MAX_RESOURCE_FINGERPRINTS) {
    return false;
  }
  const artifactIds = new Set<string>([sourceArtifactId]);
  for (const fingerprint of value) {
    if (!isFingerprint(fingerprint) || artifactIds.has(fingerprint.artifactId)) {
      return false;
    }
    artifactIds.add(fingerprint.artifactId);
  }
  return true;
}

function validIdentifier(value: unknown): value is string {
  return typeof value === 'string' && value.length <= V2_PROTOCOL_MAX_IDENTIFIER_LENGTH && identifierRegex.test(value);
}

function validOptionalIdentifier(value: unknown): value is string | undefined {
  return value === undefined || validIdentifier(value);
}

function hasOnlyKeys(value: Record<string, unknown>, keys: ReadonlySet<string>): boolean {
  return Object.keys(value).every((key) => keys.has(key));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asString(value: unknown): string {
  return typeof value === 'string' ? value : '';
}
