// <auto-generated>
// Generated by scripts/generate-v2-protocol.mjs from docs/v2/designer-protocol-v2.schema.json.
// Schema SHA-256: e80c86785fa1563da5d544561ea32efc8ab08830a57889bb85c4c535bb79e6fa
// </auto-generated>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json.Linq;

namespace WinFormsDesigner.Engine.Net48
{
    public static class V2Protocol
    {
        public const string ProtocolId = "designer-protocol-v2";
        public const int CurrentVersion = 2;
        public const int MinimumSupportedVersion = 1;
        public const int MaxPayloadBytes = 1048576;
        public const int MaxCapabilities = 64;
        public const int MaxResourceFingerprints = 64;
        public const int MaxIdentifierLength = 128;
        public const int MaxOutcomeMessageLength = 4096;
        public const string SchemaSha256 = "e80c86785fa1563da5d544561ea32efc8ab08830a57889bb85c4c535bb79e6fa";
        public const string PayloadContentType = "application/json";

        public static readonly string[] Capabilities =
        {
            "protocol.envelope-v2",
            "protocol.outcome-v2",
            "protocol.n-minus-one",
            "document.source-fingerprint",
            "document.resource-fingerprint",
            "request.deadline",
            "request.cancellation-token",
            "payload.byte-limit",
            "outcome.ok",
            "outcome.partial",
            "outcome.stale",
            "outcome.cancelled",
            "outcome.unsupported",
            "outcome.refused",
            "outcome.fault"
        };

        public static readonly string[] OutcomeCodes =
        {
            "OK",
            "PARTIAL_RESULT",
            "PARTIAL_UPDATE",
            "STALE_SOURCE",
            "STALE_RESOURCE",
            "CANCELLED",
            "UNSUPPORTED_CAPABILITY",
            "UNSUPPORTED_OPERATION",
            "UNKNOWN_REQUIRED_CAPABILITY",
            "PROTOCOL_VERSION_UNSUPPORTED",
            "PAYLOAD_TOO_LARGE",
            "INVALID_ENVELOPE",
            "INTERNAL_ERROR",
            "UNHANDLED_EXCEPTION"
        };

        private static readonly Regex IdentifierPattern = new Regex(@"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", RegexOptions.CultureInvariant);
        private static readonly Regex Sha256Pattern = new Regex(@"^[a-f0-9]{64}$", RegexOptions.CultureInvariant);
        private static readonly Regex CapabilityPattern = new Regex(@"^[a-z][a-z0-9.-]{1,95}$", RegexOptions.CultureInvariant);
        private static readonly HashSet<string> KnownCapabilities = new HashSet<string>(Capabilities, StringComparer.Ordinal);
        private static readonly HashSet<string> KnownOutcomeCodes = new HashSet<string>(OutcomeCodes, StringComparer.Ordinal);
        private static readonly HashSet<string> EnvelopeRequiredFields = new HashSet<string>(new[]
        {
            "protocolId",
            "protocolVersion",
            "messageKind",
            "buildId",
            "sessionId",
            "documentId",
            "requestId",
            "traceId",
            "documentRevision",
            "renderGeneration",
            "sourceFingerprint",
            "resourceFingerprints",
            "deadlineUnixMilliseconds",
            "cancellationToken",
            "capabilities",
            "requiredCapabilities",
            "payloadContentType",
            "payloadBytes",
            "payloadJson"
        }, StringComparer.Ordinal);
        private static readonly HashSet<string> EnvelopeAllowedFields = new HashSet<string>(new[]
        {
            "protocolId",
            "protocolVersion",
            "messageKind",
            "buildId",
            "sessionId",
            "documentId",
            "requestId",
            "traceId",
            "documentRevision",
            "renderGeneration",
            "sourceFingerprint",
            "resourceFingerprints",
            "deadlineUnixMilliseconds",
            "cancellationToken",
            "capabilities",
            "requiredCapabilities",
            "payloadContentType",
            "payloadBytes",
            "payloadJson",
            "commandId"
        }, StringComparer.Ordinal);
        private static readonly HashSet<string> FingerprintFields = new HashSet<string>(new[]
        {
            "algorithm",
            "artifactId",
            "value",
            "byteLength"
        }, StringComparer.Ordinal);

        public static V2ProtocolEnvelope CreateEnvelope(
            V2ProtocolMessageKind messageKind,
            string buildId,
            string sessionId,
            string documentId,
            string requestId,
            string traceId,
            string commandId,
            string documentRevision,
            long renderGeneration,
            V2Fingerprint sourceFingerprint,
            IReadOnlyList<V2Fingerprint> resourceFingerprints,
            long deadlineUnixMilliseconds,
            string cancellationToken,
            IReadOnlyList<string> capabilities,
            IReadOnlyList<string> requiredCapabilities,
            string payloadJson,
            int? protocolVersion = null)
        {
            return new V2ProtocolEnvelope
            {
                ProtocolId = ProtocolId,
                ProtocolVersion = protocolVersion ?? CurrentVersion,
                MessageKind = messageKind,
                BuildId = buildId,
                SessionId = sessionId,
                DocumentId = documentId,
                RequestId = requestId,
                TraceId = traceId,
                CommandId = commandId,
                DocumentRevision = documentRevision,
                RenderGeneration = renderGeneration,
                SourceFingerprint = sourceFingerprint,
                ResourceFingerprints = new List<V2Fingerprint>(resourceFingerprints ?? new V2Fingerprint[0]),
                DeadlineUnixMilliseconds = deadlineUnixMilliseconds,
                CancellationToken = cancellationToken,
                Capabilities = new List<string>(capabilities ?? new string[0]),
                RequiredCapabilities = new List<string>(requiredCapabilities ?? new string[0]),
                PayloadContentType = PayloadContentType,
                PayloadBytes = PayloadByteCount(payloadJson),
                PayloadJson = payloadJson,
            };
        }

        public static V2ProtocolValidationResult ValidateEnvelope(V2ProtocolEnvelope envelope, IReadOnlyList<string> supportedCapabilities = null)
        {
            string requestId = envelope != null && ValidIdentifier(envelope.RequestId) ? envelope.RequestId : "invalid-request";
            string traceId = envelope != null && ValidIdentifier(envelope.TraceId) ? envelope.TraceId : "invalid-trace";

            if (envelope == null)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Envelope is null."));
            if (envelope.ProtocolId != ProtocolId)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Protocol identity is invalid."));
            if (envelope.ProtocolVersion < MinimumSupportedVersion || envelope.ProtocolVersion > CurrentVersion)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "PROTOCOL_VERSION_UNSUPPORTED", "Unsupported protocol version " + envelope.ProtocolVersion + "."));
            if (envelope.MessageKind != V2ProtocolMessageKind.Request && envelope.MessageKind != V2ProtocolMessageKind.Response)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Message kind is invalid."));
            if (!ValidIdentifier(envelope.BuildId) || !ValidIdentifier(envelope.SessionId) || !ValidIdentifier(envelope.DocumentId) || !ValidIdentifier(envelope.RequestId) || !ValidIdentifier(envelope.TraceId) || !ValidOptionalIdentifier(envelope.CommandId) || !ValidIdentifier(envelope.DocumentRevision) || !ValidIdentifier(envelope.CancellationToken))
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "One or more identifiers are invalid."));
            if (envelope.RenderGeneration < 0)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Render generation is invalid."));
            if (!ValidFingerprint(envelope.SourceFingerprint) || !ValidFingerprints(envelope.ResourceFingerprints, envelope.SourceFingerprint.ArtifactId))
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Source or resource fingerprints are invalid."));
            if (envelope.DeadlineUnixMilliseconds <= 0)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Deadline is invalid."));
            if (!ValidCapabilities(envelope.Capabilities) || !ValidCapabilities(envelope.RequiredCapabilities))
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Capabilities are invalid."));

            HashSet<string> supported = new HashSet<string>(supportedCapabilities ?? Capabilities, StringComparer.Ordinal);
            string unknownRequired = FindUnknownRequiredCapability(envelope.RequiredCapabilities, supported);
            if (unknownRequired != null)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "UNKNOWN_REQUIRED_CAPABILITY", "Required capability is not supported: " + unknownRequired));

            if (envelope.PayloadContentType != PayloadContentType || envelope.PayloadJson == null)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Payload metadata is invalid."));
            int actualPayloadBytes = PayloadByteCount(envelope.PayloadJson);
            if (envelope.PayloadBytes != actualPayloadBytes)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Payload byte count does not match PayloadJson."));
            if (actualPayloadBytes > MaxPayloadBytes)
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "PAYLOAD_TOO_LARGE", "Payload exceeds the v2 envelope byte limit."));
            try
            {
                JToken.Parse(envelope.PayloadJson);
            }
            catch
            {
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Payload is not valid JSON."));
            }

            return V2ProtocolValidationResult.Accepted(envelope);
        }

        public static V2ProtocolValidationResult ValidateEnvelopeJson(string envelopeJson, IReadOnlyList<string> supportedCapabilities = null)
        {
            string requestId = "invalid-request";
            string traceId = "invalid-trace";
            try
            {
                JObject value = JToken.Parse(envelopeJson ?? string.Empty) as JObject;
                if (value == null)
                    return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Envelope JSON must be an object."));
                requestId = ValidIdentifier((string)value["requestId"]) ? (string)value["requestId"] : requestId;
                traceId = ValidIdentifier((string)value["traceId"]) ? (string)value["traceId"] : traceId;
                if (!HasClosedEnvelopeShape(value) || !HasWireEnvelopeScalarShape(value)
                    || !HasClosedFingerprintShape(value["sourceFingerprint"] as JObject))
                    return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Envelope JSON has unknown or missing fields."));
                JArray resources = value["resourceFingerprints"] as JArray;
                if (resources == null)
                    return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Resource fingerprints must be an array."));
                for (int i = 0; i < resources.Count; i++)
                {
                    if (!HasClosedFingerprintShape(resources[i] as JObject))
                        return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Resource fingerprint JSON has unknown or missing fields."));
                }
                return ValidateEnvelope(value.ToObject<V2ProtocolEnvelope>(), supportedCapabilities);
            }
            catch
            {
                return V2ProtocolValidationResult.Refused(Refusal(requestId, traceId, "INVALID_ENVELOPE", "Envelope is not valid JSON."));
            }
        }

        public static bool ValidateOutcome(V2ProtocolOutcome outcome)
        {
            return outcome != null
                && Enum.IsDefined(typeof(V2ProtocolOutcomeKind), outcome.Kind)
                && ValidIdentifier(outcome.RequestId)
                && ValidIdentifier(outcome.TraceId)
                && KnownOutcomeCodes.Contains(outcome.Code ?? string.Empty)
                && OutcomeCodeMatchesKind(outcome.Kind, outcome.Code)
                && outcome.Message != null
                && PayloadByteCount(outcome.Message) <= MaxOutcomeMessageLength
                && ValidIdentifier(outcome.DiagnosticId)
                && (outcome.ExpectedSourceFingerprint == null || ValidFingerprint(outcome.ExpectedSourceFingerprint))
                && (outcome.ActualSourceFingerprint == null || ValidFingerprint(outcome.ActualSourceFingerprint));
        }

        public static int PayloadByteCount(string payloadJson)
        {
            return Encoding.UTF8.GetByteCount(payloadJson ?? string.Empty);
        }

        public static V2Fingerprint Fingerprint(string artifactId, string sha256, long byteLength)
        {
            return new V2Fingerprint { Algorithm = "sha256", ArtifactId = artifactId, Value = sha256, ByteLength = byteLength };
        }

        private static V2ProtocolOutcome Refusal(string requestId, string traceId, string code, string message)
        {
            return new V2ProtocolOutcome
            {
                Kind = V2ProtocolOutcomeKind.Refused,
                RequestId = requestId,
                TraceId = traceId,
                Code = code,
                Message = message,
                Retryable = false,
                DiagnosticId = code,
            };
        }

        private static string FindUnknownRequiredCapability(IReadOnlyList<string> requiredCapabilities, HashSet<string> supported)
        {
            if (requiredCapabilities == null) return null;
            for (int i = 0; i < requiredCapabilities.Count; i++)
            {
                string capability = requiredCapabilities[i];
                if (!KnownCapabilities.Contains(capability) || !supported.Contains(capability))
                    return capability;
            }
            return null;
        }

        private static bool OutcomeCodeMatchesKind(V2ProtocolOutcomeKind kind, string code)
        {
            switch (kind)
            {
                case V2ProtocolOutcomeKind.Ok:
                    return code == "OK";
                case V2ProtocolOutcomeKind.Partial:
                    return code == "PARTIAL_RESULT" || code == "PARTIAL_UPDATE";
                case V2ProtocolOutcomeKind.Stale:
                    return code == "STALE_SOURCE" || code == "STALE_RESOURCE";
                case V2ProtocolOutcomeKind.Cancelled:
                    return code == "CANCELLED";
                case V2ProtocolOutcomeKind.Unsupported:
                    return code == "UNSUPPORTED_CAPABILITY" || code == "UNSUPPORTED_OPERATION";
                case V2ProtocolOutcomeKind.Refused:
                    return code == "UNKNOWN_REQUIRED_CAPABILITY" || code == "PROTOCOL_VERSION_UNSUPPORTED" || code == "PAYLOAD_TOO_LARGE" || code == "INVALID_ENVELOPE";
                case V2ProtocolOutcomeKind.Fault:
                    return code == "INTERNAL_ERROR" || code == "UNHANDLED_EXCEPTION";
                default:
                    return false;
            }
        }

        private static bool ValidIdentifier(string value)
        {
            return value != null && value.Length <= MaxIdentifierLength && IdentifierPattern.IsMatch(value);
        }

        private static bool ValidOptionalIdentifier(string value)
        {
            return value == null || ValidIdentifier(value);
        }

        private static bool ValidFingerprint(V2Fingerprint value)
        {
            return value != null
                && value.Algorithm == "sha256"
                && ValidIdentifier(value.ArtifactId)
                && value.Value != null
                && Sha256Pattern.IsMatch(value.Value)
                && value.ByteLength >= 0;
        }

        private static bool ValidFingerprints(IReadOnlyList<V2Fingerprint> values, string sourceArtifactId)
        {
            if (values == null || values.Count > MaxResourceFingerprints) return false;
            HashSet<string> artifactIds = new HashSet<string>(StringComparer.Ordinal) { sourceArtifactId };
            for (int i = 0; i < values.Count; i++)
            {
                if (!ValidFingerprint(values[i]) || !artifactIds.Add(values[i].ArtifactId)) return false;
            }
            return true;
        }

        private static bool HasClosedEnvelopeShape(JObject value)
        {
            foreach (string required in EnvelopeRequiredFields)
            {
                if (value.Property(required, StringComparison.Ordinal) == null) return false;
            }
            foreach (JProperty property in value.Properties())
            {
                if (!EnvelopeAllowedFields.Contains(property.Name)) return false;
            }
            return true;
        }

        private static bool HasWireEnvelopeScalarShape(JObject value)
        {
            string[] requiredStrings =
            {
                "protocolId", "buildId", "sessionId", "documentId", "requestId", "traceId",
                "documentRevision", "cancellationToken", "payloadContentType", "payloadJson",
            };
            for (int i = 0; i < requiredStrings.Length; i++)
            {
                if (value[requiredStrings[i]] == null || value[requiredStrings[i]].Type != JTokenType.String)
                    return false;
            }
            if (value.Property("commandId", StringComparison.Ordinal) != null
                && value["commandId"].Type != JTokenType.String)
                return false;
            if (value["messageKind"] == null || value["messageKind"].Type != JTokenType.String
                || ((string)value["messageKind"] != "request" && (string)value["messageKind"] != "response"))
                return false;
            string[] requiredIntegers =
            {
                "protocolVersion", "renderGeneration", "deadlineUnixMilliseconds", "payloadBytes",
            };
            for (int i = 0; i < requiredIntegers.Length; i++)
            {
                if (value[requiredIntegers[i]] == null || value[requiredIntegers[i]].Type != JTokenType.Integer)
                    return false;
            }
            return value["capabilities"]?.Type == JTokenType.Array
                && value["requiredCapabilities"]?.Type == JTokenType.Array
                && value["resourceFingerprints"]?.Type == JTokenType.Array;
        }

        private static bool HasClosedFingerprintShape(JObject value)
        {
            if (value == null || value.Count != FingerprintFields.Count) return false;
            foreach (string required in FingerprintFields)
            {
                if (value.Property(required, StringComparison.Ordinal) == null) return false;
            }
            return true;
        }

        private static bool ValidCapabilities(IReadOnlyList<string> values)
        {
            if (values == null || values.Count > MaxCapabilities) return false;
            HashSet<string> seen = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < values.Count; i++)
            {
                string value = values[i];
                if (value == null || !CapabilityPattern.IsMatch(value) || !seen.Add(value))
                    return false;
            }
            return true;
        }
    }

    public enum V2ProtocolMessageKind
    {
        Request,
        Response
    }

    public enum V2ProtocolOutcomeKind
    {
        Ok,
        Partial,
        Stale,
        Cancelled,
        Unsupported,
        Refused,
        Fault
    }

    public sealed class V2Fingerprint
    {
        public string Algorithm { get; set; }
        public string ArtifactId { get; set; }
        public string Value { get; set; }
        public long ByteLength { get; set; }
    }

    public sealed class V2ProtocolEnvelope
    {
        public string ProtocolId { get; set; }
        public int ProtocolVersion { get; set; }
        public V2ProtocolMessageKind MessageKind { get; set; }
        public string BuildId { get; set; }
        public string SessionId { get; set; }
        public string DocumentId { get; set; }
        public string RequestId { get; set; }
        public string TraceId { get; set; }
        public string CommandId { get; set; }
        public string DocumentRevision { get; set; }
        public long RenderGeneration { get; set; }
        public V2Fingerprint SourceFingerprint { get; set; }
        public List<V2Fingerprint> ResourceFingerprints { get; set; }
        public long DeadlineUnixMilliseconds { get; set; }
        public string CancellationToken { get; set; }
        public List<string> Capabilities { get; set; }
        public List<string> RequiredCapabilities { get; set; }
        public string PayloadContentType { get; set; }
        public int PayloadBytes { get; set; }
        public string PayloadJson { get; set; }
    }

    public sealed class V2ProtocolOutcome
    {
        public V2ProtocolOutcomeKind Kind { get; set; }
        public string RequestId { get; set; }
        public string TraceId { get; set; }
        public string Code { get; set; }
        public string Message { get; set; }
        public bool Retryable { get; set; }
        public string DiagnosticId { get; set; }
        public V2Fingerprint ExpectedSourceFingerprint { get; set; }
        public V2Fingerprint ActualSourceFingerprint { get; set; }
    }

    public sealed class V2ProtocolValidationResult
    {
        public bool Ok { get; private set; }
        public V2ProtocolEnvelope Envelope { get; private set; }
        public V2ProtocolOutcome Outcome { get; private set; }

        public static V2ProtocolValidationResult Accepted(V2ProtocolEnvelope envelope)
        {
            return new V2ProtocolValidationResult { Ok = true, Envelope = envelope };
        }

        public static V2ProtocolValidationResult Refused(V2ProtocolOutcome outcome)
        {
            return new V2ProtocolValidationResult { Ok = false, Outcome = outcome };
        }
    }
}
